export const weatherIcons = {
  "Partly cloudy": require("../assets/anim/partly-cloudy.json"),
  "Moderate rain": require("../assets/anim/rain.json"),
  "Patchy rain possible": require("../assets/anim/rain.json"),
  Sunny: require("../assets/anim/sunny.json"),
  Cloudy: require("../assets/anim/cloudy.json"),
  Clear: require("../assets/anim/sunny.json"),
  Overcast: require("../assets/anim/cloudy.json"),
  "Light rain": require("../assets/anim/rain.json"),
  "Moderate rain at times": require("../assets/anim/rain.json"),
  "Heavy rain": require("../assets/anim/rain.json"),
  "Heavy rain at times": require("../assets/anim/rain.json"),
  "Moderate or heavy freezing rain": require("../assets/anim/rain.json"),
  "Moderate or heavy rain shower": require("../assets/anim/rain.json"),
  "Moderate or heavy rain with thunder": require("../assets/anim/thunder.json"),
  other: require("../assets/anim/cloudy.json"),
};
